"""Generate atan2 lookup table for position_calc.v.

Computes atan(i/1024) mapped to 12-bit angle space (0-4095 = 0-360 degrees).
The LUT covers the first octant (0-45 degrees, indices 0-1023).
Other octants are derived by symmetry in the Verilog code.

Output: src/atan_lut.hex — 1024 lines of 3-digit hex values (12-bit).

Usage:
    python scripts/gen_atan_lut.py
"""

from __future__ import annotations

import math
from pathlib import Path


def generate_atan_lut(size: int = 1024, angle_bits: int = 12) -> list[int]:
    """Generate atan lookup table.

    For index i (0..size-1):
        ratio = i / size  (maps to 0.0 .. ~1.0)
        theta = atan(ratio)  (0 .. pi/4 radians)
        lut[i] = round(theta * 2^angle_bits / (2*pi))

    The first octant spans 0 to 45 degrees = 0 to (2^angle_bits / 8) counts.
    At 12 bits: 0 to 512 counts.
    """
    full_circle = 1 << angle_bits  # 4096
    lut = []
    for i in range(size):
        ratio = i / size
        theta_rad = math.atan(ratio)
        count = round(theta_rad * full_circle / (2 * math.pi))
        lut.append(count)
    return lut


def write_hex_file(lut: list[int], path: Path) -> None:
    """Write LUT as hex file for $readmemh."""
    with open(path, 'w') as f:
        for val in lut:
            f.write(f"{val:03X}\n")
    print(f"Written {len(lut)} entries to {path}")


def write_verilog_init(lut: list[int], path: Path) -> None:
    """Write LUT as Verilog initial block for direct embedding."""
    lines = [
        "// Auto-generated by scripts/gen_atan_lut.py",
        "// atan(i/1024) * 4096 / (2*pi) for i = 0..1023",
        "// First octant only (0-45 degrees, 0-512 counts)",
        "initial begin",
    ]
    for i, val in enumerate(lut):
        lines.append(f"    atan_lut[{i:4d}] = 12'h{val:03X}; // atan({i}/1024) = {math.degrees(math.atan(i/1024)):.2f} deg")
    lines.append("end")

    path.write_text('\n'.join(lines))
    print(f"Written Verilog init block to {path}")


def print_verification_table(lut: list[int]) -> None:
    """Print key verification points."""
    print("\nVerification table:")
    print(f"  {'Index':>6s}  {'Ratio':>8s}  {'atan(deg)':>10s}  {'LUT':>5s}  {'Expected':>8s}  {'Error':>6s}")
    print(f"  {'-----':>6s}  {'-----':>8s}  {'---------':>10s}  {'---':>5s}  {'--------':>8s}  {'-----':>6s}")

    test_indices = [0, 64, 128, 256, 362, 512, 724, 768, 1023]
    for i in test_indices:
        ratio = i / 1024
        theta_deg = math.degrees(math.atan(ratio))
        expected = math.atan(ratio) * 4096 / (2 * math.pi)
        error = abs(lut[i] - expected)
        print(f"  {i:6d}  {ratio:8.4f}  {theta_deg:10.3f}  {lut[i]:5d}  {expected:8.2f}  {error:6.2f}")


def main():
    proj_root = Path(__file__).parent.parent
    lut = generate_atan_lut()

    # Write hex file for $readmemh
    hex_path = proj_root / "src" / "atan_lut.hex"
    write_hex_file(lut, hex_path)

    # Print verification
    print_verification_table(lut)

    # Spot checks
    print(f"\nKey values:")
    print(f"  lut[0]    = {lut[0]:3d}  (atan(0)     =  0.000 deg, expect 0)")
    print(f"  lut[256]  = {lut[256]:3d}  (atan(0.25)  = 14.036 deg, expect ~160)")
    print(f"  lut[512]  = {lut[512]:3d}  (atan(0.5)   = 26.565 deg, expect ~303)")
    print(f"  lut[768]  = {lut[768]:3d}  (atan(0.75)  = 36.870 deg, expect ~420)")
    print(f"  lut[1023] = {lut[1023]:3d}  (atan(0.999) = 44.971 deg, expect ~512)")
    print(f"\n  Max LUT value: {max(lut)} (should be ~512)")
    print(f"  Linear approx would give lut[512] = {512*512//1024} (actual: {lut[512]}, error: {abs(lut[512] - 512*512//1024)})")


if __name__ == "__main__":
    main()
